### ISSUE TITLE
Feature Request: Allow opening of search results in new tabs

### ISSUE THREAD

**Issue by cookiengineer** [neo-search/urteile-gesetze-web#1]
For reference: https://github.com/neo-search/urteile-gesetze-web/blob/c94965e5340dc6170e5cce8904b9ab82ed80d3ef/components/suche/treffer/TrefferSectionSmallNorm.js#L32

The Search results page is very annoying to use, because it doesn't allow to have the results open and then have the detailed view of the results opened split-screen (or in parallel). The `click/onclick` event listener that is on the `<div class="treffer-...">` element prevents that, even when you click the `<a>` element that has a correct `href` attribute.

Steps to reproduce:

- Any Browser
- Search for something.
- Use `[Ctrl]` + `mouse click` to open the Treffer's element (or click on the a element).

**Comment by danbeck** [comment]
Fixed: CTRL + Click on a search result opens it in a new tab.
